food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from food_delivery import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('input_address/', views.InputAddress.as_view(), name='input-address'),
    path('restaurants_in_range/', views.show_restaurants_in_range, name='show_restaurants_in_range'),
    path('admin/', admin.site.urls),
    path('auth_user/', include('custom_users.urls')),
    path('restaurants/', include('restaurants.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.template.context_processors import static
from django.urls import path, include

from restaurants import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'restaurants'

urlpatterns = [
    path('add_restaurant/', views.RestaurantCreateView.as_view(), name='add-restaurant'),
    path('remove_restaurant/<str:id>/', views.remove_restaurant, name='remove-restaurant'),
    path('<str:restaurant_id>/add_dish/', views.DishCreateView.as_view(), name='add-dish'),

    path('<str:pk>/', views.restaurants, name='restaurant-page'),
    path('restaurateur/restaurants_managing/', views.restaurants_managing, name='restaurants-managing'),
    path('<str:id>/modify_restaurant/', views.modify_restaurant, name='modify-restaurant'),

    path('<str:restaurant_id_order>/orders_managing/', views.orders_managing, name='orders-managing'),
    path('<str:restaurant_id_order>/accepted_orders_managing/', views.accepted_orders_managing, name='accepted-orders-managing'),
    path('<str:restaurant_id_order>/done_orders_managing/', views.done_orders_managing, name='done-orders-managing'),
    path('<str:id>/orders_details/', views.order_details, name='orders-details'),
    path('order_done/<str:id>/', views.order_done, name='order-done'),
    path('order_accept/<str:id>/', views.order_accept, name='order-accept'),
    path('remove_order/<str:id>/', views.remove_order, name='remove-order'),
    path('checkout/payment/', views.Payment.as_view(), name='payment'),

    path('<str:id>/menu_managing/', views.menu_managing, name='menu-managing'),
    path('<str:id>/modify_dish/', views.modify_dish, name='modify-dish'),
    path('<str:id>/remove_dish/', views.remove_dish, name='remove-dish'),

    path('checkout/ajax_get_cart_data/', views.ajax_get_cart_data, name='ajax-get-cart-data'),
    path('', views.ajax_get_rating_data, name='ajax-get-rating-data'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from custom_users.models import Address
from restaurants.models import Restaurant, Order, Dish


class RestaurantForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs['placeholder'] = 'Es: Trattoria, Fast food, Braceria'
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Invia', css_class='btn btn-success')
        )

    class Meta:
        model = Restaurant
        fields = (
            'logo',
            'name',
            'category',
            'delivery_price',
            'street',
            'house_number',
            'zipcode',
            'city',
            'province',
        )
        labels = {
            'logo':             'Logo',
            'name':             'Nome del ristorante',
            'category':         'Categoria',
            'delivery_price':   'Prezzo di spedizione',
            'street':           'Via',
            'house_number':     'Numero civico',
            'zipcode':          'CAP',
            'city':             'Città',
            'province':         'Provincia',
        }


class DishForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Invia', css_class='btn btn-success')
        )

    class Meta:
        model = Dish
        fields = (
            'img',
            'name',
            'availability',
            'description',
            'price',
            'preparation_time',
        )
        labels = {
            'img':              'Immagine del piatto',
            'name':             'Nome del piatto',
            'availability':     'Dispponibilità',
            'description':      'Descrizione',
            'price':            'Prezzo',
            'preparation_time': 'Tempo di preparazione',
        }


class PaymentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Invia', css_class='btn btn-success payment-button')
        )

    class Meta:
        model = Order
        fields = (
            'customer_floor_flat_nb',
            'customer_number',
            'instructions',
            'cc_number',

        )
        labels = {
            'customer_floor_flat_nb':   'Piano e interno',
            'customer_number':          'Numero di telefono',
            'instructions':             'Istruzioni per il fattorino',
            'cc_number':                'Numero carta',
        }

restaurants/views.py
import datetime
import json

import pytz
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db import IntegrityError
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView
from django_tables2 import RequestConfig

from custom_users.models import Address, CustomUser
from food_delivery import settings
from food_delivery.email_settings import EMAIL_HOST_USER
from restaurants.forms import RestaurantForm, PaymentForm, DishForm
from restaurants.models import Dish, OrderedDish, Review
from restaurants.tables import *


# ------------------ Creation of restaurants -------------------

class RestaurantCreateView(CreateView):
    """
    Handles the creation of new restaurants
    """
    form_class = RestaurantForm
    template_name = 'restaurants/add_restaurant.html'

    def form_valid(self, form):
        restaurateur = self.request.user
        form.instance.restaurateur = restaurateur
        try:
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request, 'È già stato inserito un ristorante con questo nome!')
            return self.form_invalid(form)

    def get_success_url(self):
        messages.success(self.request, 'Nuovo ristorante aggiunto.')
        messages.warning(
            self.request,
            'I ristoranti non verranno visualizzati dai clienti fino a quando non vengono aggiunti dei piatti.'
        )
        return reverse("restaurants:restaurants-managing")

# ---------------------------------------------------------------


# ------------------ Creation of dishes -------------------

class DishCreateView(CreateView):
    """
    Handles the creation of new dishes
    """
    form_class = DishForm
    template_name = 'restaurants/add_dish.html'

    def get_context_data(self, **kwargs):
        context = super(DishCreateView, self).get_context_data(**kwargs)
        context['menu_managing_id'] = self.request.session.get('menu_managing_id', 0)
        return context

    def form_valid(self, form):
        form.instance.restaurant = Restaurant.objects.get(id=self.kwargs.get('restaurant_id', None))
        try:
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request, 'È già stato inserito un piatto con questo nome!')
            return self.form_invalid(form)

    def get_success_url(self):
        messages.success(self.request, 'Nuovo piatto aggiunto.')
        return reverse("restaurants:menu-managing", args=(self.kwargs.get('restaurant_id', None),))

# ----------------------------------------------------------


# ------------------ Restaurants management -------------------

def get_max_delivery_time(restaurant, travel_time):
    """
    Returns the delivery time calculated as the maximum preparation time for the dishes plus the travel time
    from the restaurant to the customer's house
    :param restaurant: restaurant
    :param travel_time: travel time from the restaurant to the customer's house
    :return: delivery time in minutes
    """
    restaurant_dishes = Dish.objects.filter(restaurant=restaurant).filter(availability=True)
    max_preparation_time = 0
    for dish in restaurant_dishes:
        if dish.preparation_time > max_preparation_time:
            max_preparation_time = dish.preparation_time
    return max_preparation_time + travel_time


def restaurants(request, pk):
    """
    Shows the restaurant page with his data, the distance and travel time from the customer, the average rating,
    the dishes, the shopping cart, the rating input system (that can only be accessed by authenticated customers that
    made an order to the restaurant) and all the past ratings (that can only be accessed by authenticated customers)
    """
    restaurant = Restaurant.objects.get(id=pk)
    request.session['restaurant_id'] = restaurant.id
    dishes = Dish.objects.filter(restaurant=pk)
    user = request.user
    user_authenticated = False
    if user.is_authenticated:
        user_authenticated = True
    user_address = request.session.get('input_address', None)

    # Delivery info
    distance_duration = request.session.get('distance_duration'+pk.__str__(), None)
    if request.user.is_authenticated and request.user.is_restaurateur:
        delivery_time = '*Tempi di spedizione*'
        distance = '*Distanza*'
    else:
        distance = round(distance_duration.get('distance', None), 1)
        travel_time = distance_duration.get('duration', None)
        request.session['travel_time'] = travel_time
        delivery_time = int(get_max_delivery_time(restaurant, travel_time))
        # request.session['delivery_time'] = delivery_time

    # Cart info
    cart_elements_dict = request.session.get('cart_elements', None)
    cart_elements = list()
    cart_restaurant = ''
    if cart_elements_dict != None:
        cart_elements = cart_elements_dict.get('elements', {})
        cart_restaurant = int(cart_elements_dict.get('restaurant', '0'))

    # Review info
    user_made_order = False
    user_reviewed_restaurant = False
    user_review = []
    user = request.user
    if user.is_authenticated:
        order = Order.objects.filter(restaurant=restaurant).filter(customer=user)
        if len(order) != 0:
            user_made_order = True
        user_reviews = Review.objects.filter(reviewer=user)
        if len(user_reviews) != 0:
            user_review = user_reviews.filter(restaurant=restaurant)
        if len(user_review) != 0:
            user_reviewed_restaurant = True
            user_review = user_reviews.get(restaurant=restaurant)
        user_name = user.first_name
    else:
        user_name = ''
    reviews = Review.objects.filter(restaurant=restaurant.id)

    # Rating info
    ratings_total = 0
    reviews_number = len(reviews)
    for rating in reviews.values_list('rating', flat=True):
        ratings_total += rating
    if reviews_number != 0:
        average_rating = round(ratings_total/len(reviews), 1)
    else:
        average_rating = 0
    if user_authenticated and user_reviewed_restaurant:
        user_rating = reviews.get(reviewer=user).rating
    else:
        user_rating = None

    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)

    context = {
        'restaurant': restaurant, 'dishes': dishes, 'media_url': settings.MEDIA_URL, 'user_address': user_address,
        'delivery_time': delivery_time, 'cart_restaurant': cart_restaurant, 'cart_elements': cart_elements,
        'cart_elements_number': len(cart_elements), 'user_made_order': user_made_order,
        'user_reviewed_restaurant': user_reviewed_restaurant, 'user_review': user_review,
        'user_authenticated': user_authenticated, 'reviews': reviews, 'stars_number': [1,2,3,4,5],
        'average_rating': average_rating, 'reviews_number': reviews_number, 'distance': distance,
        'cart_total': cart_total, 'user_name': user_name, 'user_rating': user_rating
    }

    return render(request, 'restaurants/restaurant_page.html', context)


def modify_restaurant(request, id=None, template_name='restaurants/modify_restaurant.html'):
    """
    Handles the modification of a restaurant
    """
    if id:
        restaurant = get_object_or_404(Restaurant, pk=id)
        if restaurant.restaurateur != request.user:
            return HttpResponseForbidden()
    else:
        return

    form = RestaurantForm(request.POST or None, instance=restaurant)
    if request.POST and form.is_valid():
        form.save()

        # Save was successful, so redirect to another page
        messages.success(request, 'Ristorante modificato.')
        redirect_url = reverse('restaurants:restaurants-managing')
        return redirect(redirect_url)

    name = restaurant.name
    return render(request, template_name, {
        'form': form,
        'name': name,
    })


def remove_restaurant(request, id):
    """
    Handles the removal of a restaurant
    """
    Restaurant.objects.get(id=id).delete()
    messages.success(request, 'Ristorante rimosso.')
    return redirect('restaurants:restaurants-managing')


def restaurants_managing(request):
    """
    Shows the restaurateur all the restaurants that he added to the platform and gives him the opportunity to modify
    them, delete them or add new ones.
    """
    restaurateurs_restaurants = Restaurant.objects.filter(restaurateur=request.user)
    restaurants_number = len(restaurateurs_restaurants)
    table = RestaurantsTable(restaurateurs_restaurants)
    RequestConfig(request).configure(table)
    context = {'table': table, 'user_name': request.user.first_name, 'restaurants_number': restaurants_number}
    return render(request, 'restaurants/restaurants_managing.html', context)

# ---------------------------------------------------------


# ------------------ Menu management -------------------

def menu_managing(request, id=0):
    """
    Shows the restaurateur all the dishes that he added to the restaurants and gives him the opportunity to modify
    them, delete them or add new ones.
    """
    request.session['menu_managing_id'] = id
    restaurateurs_restaurants = Restaurant.objects.filter(restaurateur=request.user)
    if id.__str__() == '0':
        restaurateurs_menu = Dish.objects.filter(restaurant=restaurateurs_restaurants[0])
        restaurant = restaurateurs_restaurants[0]
    else:
        restaurateurs_menu = Dish.objects.filter(restaurant=id.__str__())
        restaurant = Restaurant.objects.get(id=id)
    multiple_restaurants = False
    if len(restaurateurs_restaurants) > 1:
        multiple_restaurants = True
    dishes_number = len(restaurateurs_menu)
    table = MenuTable(restaurateurs_menu)

restaurants/templates/restaurants/accepted_orders_managing.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/managing_pages.css' %}">
{% endblock %}

{% block title %}Gestione ordini accettati{% endblock %}

{% block search-bar %}
{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <div class="row managing-pages-head m-2">
        <h2>Gestione ordini accettati dal ristorante {{ restaurant.name }}</h2>
    </div>
    {% if multiple_restaurants %}
        <ul class="nav-item dropdown px-0 select-restaurant-dropdown">
            <aX class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Seleziona ristorante
            </aX>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for restaurant in restaurateurs_restaurants %}
                    <a class="dropdown-item" href="{% url 'restaurants:accepted-orders-managing' restaurant.id %}">{{ restaurant.name }}</a>
                {% endfor %}
                {#                <a class="dropdown-item" href="{% url 'restaurants:orders-managing' %}">Gestione ordini</a>#}
            </div>
        </ul>
    {% endif %}
    {% if orders_number == 0 %}
        <p>Non sono presenti ordini per questo ristorante</p>
    {% else %}
        {% render_table table %}
    {% endif %}
{% endblock %}

restaurants/templates/restaurants/done_orders_managing.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/managing_pages.css' %}">
{% endblock %}

{% block title %}Gestione ordini{% endblock %}

{% block search-bar %}
{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <div class="row managing-pages-head m-2">
        <h2>Gestione ordini terminati dal ristorante {{ restaurant.name }}</h2>
    </div>
    {% if multiple_restaurants %}
        <ul class="nav-item dropdown px-0 select-restaurant-dropdown">
            <aX class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Seleziona ristorante
            </aX>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for restaurant in restaurateurs_restaurants %}
                    <a class="dropdown-item" href="{% url 'restaurants:done-orders-managing' restaurant.id %}">{{ restaurant.name }}</a>
                {% endfor %}
                {#                <a class="dropdown-item" href="{% url 'restaurants:orders-managing' %}">Gestione ordini</a>#}
            </div>
        </ul>
    {% endif %}
    {% if orders_number == 0 %}
        <p>Non sono presenti ordini per questo ristorante</p>
    {% else %}
        {% render_table table %}
    {% endif %}
{% endblock %}

restaurants/templates/restaurants/menu_managing.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/managing_pages.css' %}">
{% endblock %}

{% block title %}Gestione menu del ristorante {{ restaurant.name }}{% endblock %}

{% block search-bar %}
{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->
    <div class="row managing-pages-head mt-2">
        <h2 class="m-0">Gestione menu del ristorante {{ restaurant.name }}</h2>
    </div>

    <div class="row add-item">
        <a class="btn btn-primary m-4" href="{% url 'restaurants:add-dish' restaurant.id %}">
            <i class='fas fa-plus mr-1'></i>
            Aggiungi piatto
        </a>
    </div>

    {% if multiple_restaurants %}
        <ul class="nav-item dropdown px-0 select-restaurant-dropdown">
            <aX class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Seleziona ristorante
            </aX>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for restaurant in restaurateurs_restaurants %}
                    <a class="dropdown-item" href="{% url 'restaurants:menu-managing' restaurant.id %}">{{ restaurant.name }}</a>
                {% endfor %}
            </div>
        </ul>
    {% endif %}

    {% if dishes_number == 0 %}
        <p>Non sono stati inseriti piatti per questo ristorante</p>
    {% else %}
        {% render_table table %}
    {% endif %}
{% endblock %}

restaurants/templates/restaurants/order_details.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block title %}Dettagli ordine{% endblock %}

{% block body %}
    {% if order_managing_type == 'done' %}
        <a type="button"  href="{% url 'restaurants:done-orders-managing' order_managing_id %}" class="btn btn-outline-dark"><i class="fas fa-arrow-left mr-2"></i>Torna alla gestione ordini</a>
    {% elif order_managing_type == 'accepted' %}
        <a type="button"  href="{% url 'restaurants:accepted-orders-managing' order_managing_id %}" class="btn btn-outline-dark"><i class="fas fa-arrow-left mr-2"></i>Torna alla gestione ordini</a>
    {% else %}
    <a type="button"  href="{% url 'restaurants:orders-managing' order_managing_id %}" class="btn btn-outline-dark"><i class="fas fa-arrow-left mr-2"></i>Torna alla gestione ordini</a>
    {% endif %}

    <h2>Dettagli ordine per il ristorante {{ order.restaurant.name }}</h2>
    <b>Data ordine: </b>
    <p>{{ order.timestamp }}</p>
    <b>Cliente: </b>
    <p>
        email: {{ order.customer }}
        <br>
        Telefono: {{ order.customer_number }}
    </p>
    <b>Indirizzo:</b>
    <p>
        Via {{ order.customer_address.street }}
        n°{{ order.customer_address.house_number }},
        {{ order.customer_address.city }} ({{ order.customer_address.province }})
        <br>
        Piano: {{ order.customer_floor_flat_nb }}
        <br>
        Istruzioni per il fattorino: {{ order.instructions }}
    </p>
    <b>Piatti ordinati:</b>
    {% for dish in ordered_dishes %}
        <p>  - {{ dish.quantity }} {{ dish.name }}, prezzo: {{ dish.price }}€</p>
    {% endfor %}
    <b>Totale:</b>
    <p>{{ order.price }}€</p>
{% endblock %}

restaurants/templates/restaurants/orders_managing.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/managing_pages.css' %}">
{% endblock %}

{% block title %}Gestione ordini{% endblock %}

{% block search-bar %}
{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <div class="row managing-pages-head m-2">
        <h2>Gestione ordini per il ristorante  {{ restaurant.name }}</h2>
    </div>
    {% if multiple_restaurants %}
        <ul class="nav-item dropdown px-0 select-restaurant-dropdown">
            <aX class="nav-link dropdown-toggle" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Seleziona ristorante
            </aX>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for restaurant in restaurateurs_restaurants %}
                    <a class="dropdown-item" href="{% url 'restaurants:orders-managing' restaurant.id %}">{{ restaurant.name }}</a>
                {% endfor %}
            </div>
        </ul>
    {% endif %}
    {% if orders_number == 0 %}
        <p>Non sono presenti ordini per questo ristorante</p>
    {% else %}
        {% render_table table %}
    {% endif %}
{% endblock %}

restaurants/templates/restaurants/payment.html
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/payment.css' %}">
{% endblock %}

{% block title %}Pagamento{% endblock %}

{% block body %}
    <a type="button"  href="{% url 'restaurants:restaurant-page' restaurant_id %}" class="btn btn-outline-dark"><i class="fas fa-arrow-left mr-2"></i>Torna al ristorante</a>

    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <!------------------------ SHOPPING CART ------------------------>
    <div class="container">
        <div class="card shopping-cart my-lg-2 my-md-2 my-sm-2" id="shopping_cart">
            <div class="card-header bg-dark text-light">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Carrello
                <div class="clearfix"></div>
            </div>
            <div class="card-body cart-items">
                <!-- cart elements -->
                {% for element in cart_elements %}
                    <div class="row cart-row">
                        <div class="col-4 col-sm-4 col-md-4">
                            <div class="quantity">
                                <!--                        <input type="button" value="+" class="dish-item-plus">-->
                                <input value={{ element.dish_quantity }} class="dish-item-qty"
                                       size="4" disabled>
                                <!--                        <input type="button" value="-" class="dish-item-minus">-->
                            </div>
                        </div>
                        <div class="col-4 text-sm-center col-sm-4 text-md-left col-md-4">
                            <p class="product-name">{{ element.dish_name }}</p>
                        </div>
                        <div class="col-4 col-sm-4 text-sm-center col-md-4 text-md-right row">
                            <div class="col-10 col-sm-10 col-md-10 text-md-right" style="padding-top: 5px">
                                <!--   <script class="dish-original-price">var dishPrice = ${price}</script> -->
                                <p class="dish-item-price" data-original-price='{{ element.price }}'>{% widthratio element.price 1 element.dish_quantity %}€</p>
                            </div>
                            <hr>
                        </div>
                    </div>
                {% endfor %}
                <!------------------->

            </div>
            <div class="card-footer">
                <div class="pull-right" style="margin: 10px">
                    <div class="pull-left" style="margin: 5px">
                        <p class="delivery-price my-1">Consegna: {{ delivery_price }}€</p>
                        <p class="my-1">Totale: <b class="cart-total-price">{{ cart_total }}€</b></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <!------------------------------------------------>

    <div class="container">
        {% csrf_token %}
        {% crispy form %}
    </div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/cart_updater.js' %}"></script>
{% endblock %}

restaurants/templates/restaurants/restaurants_managing.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/managing_pages.css' %}">
{% endblock %}

{% block title %}Gestione ristoranti{% endblock %}

{% block search-bar %}
{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <div class="row managing-pages-head mt-2">
        <h2 class="m-0">Gestione ristoranti</h2>
    </div>

    <div class="row add-item">
        <a class="btn btn-primary m-4" href="{% url 'restaurants:add-restaurant' %}">
            <i class='fas fa-plus mr-1'></i>
            Aggiungi ristorante
        </a>
    </div>

    {% if restaurants_number == 0 %}
        <p>Non è stato inserito alcun ristorante</p>
    {% else %}
        {% render_table table %}
    {% endif %}
{% endblock %}