custom_users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from custom_users import views

app_name = 'custom_users'

urlpatterns = [
    path('customer_home/', views.customer_home, name='customer-home'),
    path('restaurateur_home/', views.restaurateur_home, name='restaurateur-home'),
    path('customer_users/register/', views.CustomerUserCreateView.as_view(), name='register-customer-user'),

    path('restaurateur_users/register/', views.RestaurateurUserCreateView.as_view(), name='register-restaurateur-user'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('customer_orders_managing/', views.customer_orders_managing, name='customer-orders-managing'),
    path('customer_accepted_orders_managing/', views.customer_accepted_orders, name='customer-accepted-orders'),
    path('<str:id>/customer_order_details/', views.customer_order_details, name='customer-order-details'),
    path('<str:id>/customer_modify_order/', views.customer_modify_order, name='customer-modify-order'),
    path('<str:id>/customer_cancel_order/', views.customer_cancel_order, name='customer-cancel-order'),
    path('<str:id>/customer_order_remove/', views.customer_order_remove, name='customer-order-remove'),

    path('modify_order/ajax_get_cart_data/', views.ajax_get_cart_data, name='ajax-get-cart-data'),

]

food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from food_delivery import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('input_address/', views.InputAddress.as_view(), name='input-address'),
    path('restaurants_in_range/', views.show_restaurants_in_range, name='show_restaurants_in_range'),
    path('admin/', admin.site.urls),
    path('auth_user/', include('custom_users.urls')),
    path('restaurants/', include('restaurants.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.template.context_processors import static
from django.urls import path, include

from restaurants import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'restaurants'

urlpatterns = [
    path('add_restaurant/', views.RestaurantCreateView.as_view(), name='add-restaurant'),
    path('remove_restaurant/<str:id>/', views.remove_restaurant, name='remove-restaurant'),
    path('<str:restaurant_id>/add_dish/', views.DishCreateView.as_view(), name='add-dish'),

    path('<str:pk>/', views.restaurants, name='restaurant-page'),
    path('restaurateur/restaurants_managing/', views.restaurants_managing, name='restaurants-managing'),
    path('<str:id>/modify_restaurant/', views.modify_restaurant, name='modify-restaurant'),

    path('<str:restaurant_id_order>/orders_managing/', views.orders_managing, name='orders-managing'),
    path('<str:restaurant_id_order>/accepted_orders_managing/', views.accepted_orders_managing, name='accepted-orders-managing'),
    path('<str:restaurant_id_order>/done_orders_managing/', views.done_orders_managing, name='done-orders-managing'),
    path('<str:id>/orders_details/', views.order_details, name='orders-details'),
    path('order_done/<str:id>/', views.order_done, name='order-done'),
    path('order_accept/<str:id>/', views.order_accept, name='order-accept'),
    path('remove_order/<str:id>/', views.remove_order, name='remove-order'),
    path('checkout/payment/', views.Payment.as_view(), name='payment'),

    path('<str:id>/menu_managing/', views.menu_managing, name='menu-managing'),
    path('<str:id>/modify_dish/', views.modify_dish, name='modify-dish'),
    path('<str:id>/remove_dish/', views.remove_dish, name='remove-dish'),

    path('checkout/ajax_get_cart_data/', views.ajax_get_cart_data, name='ajax-get-cart-data'),
    path('', views.ajax_get_rating_data, name='ajax-get-rating-data'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from custom_users.models import CustomUser


class CustomerUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Nome'
        self.fields['email'].widget.attrs['placeholder'] = 'example@example.com'
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Crea un account', css_class='btn btn-success')
        )

    class Meta:
        model = CustomUser
        fields = (
            'first_name',
            'email',
            'password1',
            'password2',
        )
        labels = {
            'first_name': 'Nome',
            'email'     : 'email',
            'password1' : 'Password',
            'password2' : 'Ripeti password'
        }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.save()
        return user


class RestaurateurUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'name'
        self.fields['email'].widget.attrs['placeholder'] = 'example@example.com'
        self.fields['password1'].widget.attrs['placeholder'] = 'choose your password wisely'
        self.fields['password2'].widget.attrs['placeholder'] = 'repeat your chosen password'
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Crea un account', css_class='btn btn-success')
        )

    class Meta:
        model = CustomUser
        fields = (
            'first_name',
            'email',
            'password1',
            'password2',
        )

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_restaurateur = True
        user.save()
        return user

custom_users/views.py
import json

from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.core.mail import send_mail
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse, resolve
from django.views.generic import CreateView
from django_tables2 import RequestConfig

from custom_users.forms import CustomerUserCreationForm, RestaurateurUserCreationForm
from custom_users.tables import CustomerOrdersTable, CustomerAcceptedOrdersTable
from food_delivery.email_settings import EMAIL_HOST_USER
from restaurants.forms import PaymentForm
from restaurants.models import Order, Dish, OrderedDish


def customer_home(request):
    """
    Renders the home dedicated to the customer
    """
    user_name = request.user.first_name
    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)
    context = {'user_name': user_name, 'cart_total': cart_total}
    return render(request, 'home.html', context)


def restaurateur_home(request):
    """
    Renders the home dedicated to the customer
    """
    user_name = request.user.first_name
    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)
    context = {'user_name': user_name, 'cart_total': cart_total}
    return render(request, 'custom_users/restaurateur_home.html', context)


def customer_orders_managing(request):
    """
    Shows the customer the orders that have been made and gives him the possibility to modify or cancel them
    """
    customers_orders = Order.objects.filter(customer=request.user).filter(deleted_by_customer=False).filter(accepted=False)
    orders_number = len(customers_orders)
    table = CustomerOrdersTable(customers_orders)
    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)
    request.session['details_previous'] = resolve(request.get_full_path()).url_name
    RequestConfig(request).configure(table)
    context = {'table': table, 'user_name': request.user.first_name, 'orders_number': orders_number,
               'cart_total': cart_total}
    return render(request, 'custom_users/customer_orders_managing.html', context)


def customer_accepted_orders(request):
    """
    Shows the customer the accepted orders and gives him the possibility to delete them
    """
    customers_orders = Order.objects.filter(customer=request.user).filter(deleted_by_customer=False).filter(accepted=True)
    orders_number = len(customers_orders)
    table = CustomerAcceptedOrdersTable(customers_orders)
    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)
    request.session['details_previous'] = resolve(request.get_full_path()).url_name
    RequestConfig(request).configure(table)
    context = {'table': table, 'user_name': request.user.first_name, 'orders_number': orders_number,
               'cart_total': cart_total}
    return render(request, 'custom_users/customer_accepted_orders_managing.html', context)


def customer_order_details(request, id):
    """
    Shows the details of the order selected by the customer
    """
    order = Order.objects.get(id=id)
    ordered_dishes_ref = OrderedDish.objects.filter(order=order)
    ordered_dishes = list()
    for ordered_dish in ordered_dishes_ref:
        dish = Dish.objects.get(id=ordered_dish.dish.id)
        dishes_dict = dict()
        dishes_dict['name'] = dish.name
        dishes_dict['quantity'] = ordered_dish.quantity
        dishes_dict['price'] = dish.price * ordered_dish.quantity
        ordered_dishes.append(dishes_dict)
    details_previous = request.session.get('details_previous', 'customer-orders-managing')
    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)
    previous = 'custom_users:' + details_previous.__str__()
    context = {'order': order, 'ordered_dishes': ordered_dishes, 'user_name': request.user.first_name,
               'previous': previous, 'cart_total': cart_total}
    return render(request, 'custom_users/customer_order_details.html', context)


def customer_modify_order(request, id=None, template_name='custom_users/customer_modify_order.html'):
    """
    Handles the order modification. Only the parameters of the Order objects, not the OrderedDish ones.
    """
    if id:
        order = get_object_or_404(Order, pk=id)
        request.session['order_id'] = order.id
        if order.customer != request.user:
            return HttpResponseForbidden()
    else:
        return

    form = PaymentForm(request.POST or None, instance=order)
    if request.POST and form.is_valid():
        form.save()

        # Save was successful, so redirect to another page
        messages.success(request, 'Ordine modificato.')
        redirect_url = reverse('custom_users:customer-orders-managing')
        return redirect(redirect_url)

    ordered_dishes = OrderedDish.objects.filter(order=order)
    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)
    context = {'ordered_dishes': ordered_dishes, 'form': form, 'order': order, 'user_name': request.user.first_name,
               'cart_total': cart_total}
    return render(request, template_name, context)


def customer_cancel_order(request, id):
    """
    Handles the cancellation of an order by the customer
    """
    order = Order.objects.get(id=id)

    # Sends a notification email to the restaurateur
    cart_elements = OrderedDish.objects.filter(order=order)
    delivery_price = order.price
    message = "L'ordine n°" + order.id.__str__() + " effettuato dall'utente " + order.customer.email.__str__() + \
              " e comprendente:\n\n"
    for element in cart_elements:
        quantity = element.quantity
        name = element.dish.name
        price = element.dish.price
        message += '- ' + quantity.__str__() + \
                   ' ' + name.__str__() + ',\n'
    message += "\nper un totale di € " + delivery_price.__str__()
    message += "è stato disdetto.\n"
    send_mail(
        "Disdetta ordine",
        message,
        EMAIL_HOST_USER,
        [order.restaurant.restaurateur.email],
        fail_silently=False,
    )

    order.delete()
    messages.info(request, 'Ordine disdetto.')
    return redirect(request.META.get('HTTP_REFERER'))


def customer_order_remove(request, id):
    """
    Handles the orders' removal
    """
    order = Order.objects.get(id=id)
    order.deleted_by_customer = True
    order.save()
    messages.success(request, 'Ordine eliminato.')
    return redirect(request.META.get('HTTP_REFERER'))


# ------------------ User -------------------

class CustomerUserCreateView(CreateView):
    """
    Handles the creation of a new customer user
    """
    form_class = CustomerUserCreationForm
    template_name = 'registration/create_custom_user.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        response = super(CustomerUserCreateView, self).form_valid(form)
        self.object.save()

        messages.info(self.request, 'Nuovo utente creato con successo')
        return redirect('custom_users:login')


class RestaurateurUserCreateView(CreateView):
    """
    Handles the creation of a new restaurateur
     user
    """
    form_class = RestaurateurUserCreationForm
    template_name = 'registration/create_custom_user.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        response = super(RestaurateurUserCreateView, self).form_valid(form)
        self.object.save()

        messages.info(self.request, 'Nuovo utente ristoratore creato con successo')
        return redirect('custom_users:login')


class CustomLoginView(auth_views.LoginView):
    """
    Handles the authentication of the users redirecting to the payment page if they tried to access it without
    authentication otherwise redirecting to the homepage and cleaning the shopping cart.
    """

    def get_context_data(self, **kwargs):
        context = super(CustomLoginView, self).get_context_data(**kwargs)
        context['previous_url'] = self.request.META.get('HTTP_REFERER')
        return context
    def form_valid(self, form):

        url = self.request.GET.get("next")
        if url and form.get_user().is_restaurateur:
            messages.error(self.request, 'Solo gli utenti registrati come clienti possono accedere al pagamento.')
            return redirect(url)
        else:
            return super().form_valid(form)

    def get_success_url(self):
        url = self.request.GET.get("next")
        messages.success(self.request, 'Login effettuato con successo')
        if url:
            if self.request.user.is_customer:
                return reverse('restaurants:payment')
        else:
            self.request.session['cart_elements'] = {}
            return reverse('home')


# -------------------- AJAX ------------------

def ajax_get_cart_data(request):
    """
    Gets the cart data from the Ajax function in customer_modify_order.html.
    The customer can modify the order only if the restaurateur hasn't accepted it, so there is a locking system
    that doesn't allow the customer to make modifications if the order is locked (that meas the restaurateur is
    accepting it in the same moment).
    If the order isn't locked all the data is checked and if the number of dishes ordered is changed the restaurateur
    is notified.
    """
    order_id = request.session.get('order_id', '')
    order = Order.objects.get(id=order_id)

    # If the restaurateur is accepting the order, the order is locked and the customer can't modify it
    if order.lock:
        correct = False
        data = {
            'correct': correct,
            'message': 'Si è verificato un accesso simultaneo alla modifica di questo ordine.'
        }
        return JsonResponse(data)
    else:
        order.lock = True
        order.save()

    cart_elements_str = request.POST.get('elements', {})
    cart_elements = json.loads(cart_elements_str)

custom_users/templates/custom_users/customer_accepted_orders_managing.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block title %}Gestione ordini accettati{% endblock %}


{% block body %}
        <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <h2>Gestione ordini presi in carico dal ristorante</h2>
    {% if orders_number == 0 %}
        <p>Non sono presenti ordini per questo ristorante</p>
    {% else %}
        {% render_table table %}
    {% endif %}
{% endblock %}

custom_users/templates/custom_users/customer_modify_order.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Modifica ordine{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/restaurants.css' %}">
    <link rel="stylesheet" href="{% static 'css/shopping_cart.css' %}">
{% endblock %}

{% block body %}
    <a type="button"  href="{% url 'custom_users:customer-orders-managing' %}" class="btn btn-outline-dark"><i class="fas fa-arrow-left mr-2"></i>Torna alla gestione ordini</a>

    <!------------------------ SHOPPING CART ------------------------>
    <div class="container">
        <div class="card shopping-cart my-lg-2 my-md-2 my-sm-2" id="shopping_cart">
            <div class="card-header bg-dark text-light">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Carrello
                <div class="clearfix"></div>
            </div>
            <div class="card-body cart-items">
                <!-- cart elements -->
                {% for dish in ordered_dishes  %}
                    <div class="row cart-row">
                        <div class="col-4 col-sm-4 col-md-4">
                            <div class="quantity">
                                {#                                    <input type="button" value="+" class="dish-item-plus">#}
                                <input value={{ dish.quantity }} class="dish-item-qty"
                                       size="4">
                                {#                                    <input type="button" value="-" class="dish-item-minus">#}
                            </div>
                        </div>
                        <div class="col-4 text-sm-center col-sm-4 text-md-left col-md-4">
                            <p class="product-name">{{ dish.dish.name }}</p>
                        </div>
                        <div class="col-4 col-sm-4 text-sm-center col-md-4 text-md-right row">
                            <div class="col-10 col-sm-10 col-md-10 text-md-right" style="padding-top: 5px">
                                <!--   <script class="dish-original-price">var dishPrice = ${price}</script> -->
                                <p class="dish-item-price" data-original-price='{{ dish.dish.price }}'>{% widthratio dish.dish.price 1 dish.quantity %}€</p>
                            </div>
                            <hr>
                        </div>
                    </div>
                {% endfor %}
                <!------------------->
            </div>
            <div class="card-footer">
                <div class="pull-right" style="margin: 10px">
                    <div class="pull-left" style="margin: 5px">
                        <p class="delivery-price my-1">Consegna: {{ order.restaurant.delivery_price }}€</p>
                        <p class="my-1">Totale: <b class="cart-total-price">{{ order.price }}€</b></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!------------------------------------------------>

    <div class="container">
        {% csrf_token %}
        {% crispy form %}
    </div>
{% endblock %}

{% block javascript %}
    <script>
        let cart_button = false
    </script>
    <script type="text/javascript" src="{% static 'js/cart_updater.js' %}"></script>
    <script type="text/javascript">
        console.log('elements', elements)
        updateCartTotal()
        $('.payment-button').click(function() {
            $.ajax({
                type: "POST",
                async: false,
                url: '{% url "custom_users:ajax-get-cart-data" %}',
                data: {
                    'elements': JSON.stringify(elements),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                dataType: 'json',
                success: function(data) {
                    if (data.correct) {
                        console.log('Dati del carrello inviati correttamente')
                    } else {
                        alert(data.message)
                    }
                },
                error:function() {
                    console.log('ajax error')
                }
            });
        })
    </script>
{% endblock %}

custom_users/templates/custom_users/customer_order_details.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block title %}Dettagli ordine{% endblock %}

{% block body %}
    <a type="button"  href="{% url previous %}" class="btn btn-outline-dark"><i class="fas fa-arrow-left mr-2"></i>Torna alla gestione ordini</a>
    <h2>Dettagli ordine per il ristorante {{ order.restaurant.name }}</h2>
    <b>Data ordine: </b>
    <p>{{ order.timestamp }}</p>
    <b>Stima dell'arrivo:</b>
    <p>{{ order.arrival_time }}</p>
    <b>Cliente: </b>
    <p>{{ order.customer }}</p>
    <b>Indirizzo:</b>
    <p>
        Via {{ order.customer_address.street }}
        n°{{ order.customer_address.house_number }},
        {{ order.customer_address.city }} ({{ order.customer_address.province }})
    </p>
    <br>
    <b>Piatti ordinati:</b>
    {% for dish in ordered_dishes %}
        <p>  - {{ dish.quantity }} {{ dish.name }}, prezzo: {{ dish.price }}€</p>
    {% endfor %}
    <b>Totale:</b>
    <p>{{ order.price }}€</p>
{% endblock %}

custom_users/templates/custom_users/customer_orders_managing.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}
{% load django_tables2 %}

{% block title %}Gestione ordini{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <h2>Gestione ordini</h2>
    {% if orders_number == 0 %}
        <p>Non sono presenti ordini per questo ristorante</p>
    {% else %}
        {% render_table table %}
    {% endif %}
{% endblock %}

custom_users/templates/custom_users/restaurateur_home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Homepage{% endblock %}

{% block search-bar %}
{% endblock %}