food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from food_delivery import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('input_address/', views.InputAddress.as_view(), name='input-address'),
    path('restaurants_in_range/', views.show_restaurants_in_range, name='show_restaurants_in_range'),
    path('admin/', admin.site.urls),
    path('auth_user/', include('custom_users.urls')),
    path('restaurants/', include('restaurants.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.template.context_processors import static
from django.urls import path, include

from restaurants import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'restaurants'

urlpatterns = [
    path('add_restaurant/', views.RestaurantCreateView.as_view(), name='add-restaurant'),
    path('remove_restaurant/<str:id>/', views.remove_restaurant, name='remove-restaurant'),
    path('<str:restaurant_id>/add_dish/', views.DishCreateView.as_view(), name='add-dish'),

    path('<str:pk>/', views.restaurants, name='restaurant-page'),
    path('restaurateur/restaurants_managing/', views.restaurants_managing, name='restaurants-managing'),
    path('<str:id>/modify_restaurant/', views.modify_restaurant, name='modify-restaurant'),

    path('<str:restaurant_id_order>/orders_managing/', views.orders_managing, name='orders-managing'),
    path('<str:restaurant_id_order>/accepted_orders_managing/', views.accepted_orders_managing, name='accepted-orders-managing'),
    path('<str:restaurant_id_order>/done_orders_managing/', views.done_orders_managing, name='done-orders-managing'),
    path('<str:id>/orders_details/', views.order_details, name='orders-details'),
    path('order_done/<str:id>/', views.order_done, name='order-done'),
    path('order_accept/<str:id>/', views.order_accept, name='order-accept'),
    path('remove_order/<str:id>/', views.remove_order, name='remove-order'),
    path('checkout/payment/', views.Payment.as_view(), name='payment'),

    path('<str:id>/menu_managing/', views.menu_managing, name='menu-managing'),
    path('<str:id>/modify_dish/', views.modify_dish, name='modify-dish'),
    path('<str:id>/remove_dish/', views.remove_dish, name='remove-dish'),

    path('checkout/ajax_get_cart_data/', views.ajax_get_cart_data, name='ajax-get-cart-data'),
    path('', views.ajax_get_rating_data, name='ajax-get-rating-data'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from custom_users.models import Address
from restaurants.models import Restaurant, Order, Dish


class RestaurantForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs['placeholder'] = 'Es: Trattoria, Fast food, Braceria'
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Invia', css_class='btn btn-success')
        )

    class Meta:
        model = Restaurant
        fields = (
            'logo',
            'name',
            'category',
            'delivery_price',
            'street',
            'house_number',
            'zipcode',
            'city',
            'province',
        )
        labels = {
            'logo':             'Logo',
            'name':             'Nome del ristorante',
            'category':         'Categoria',
            'delivery_price':   'Prezzo di spedizione',
            'street':           'Via',
            'house_number':     'Numero civico',
            'zipcode':          'CAP',
            'city':             'Città',
            'province':         'Provincia',
        }


class DishForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Invia', css_class='btn btn-success')
        )

    class Meta:
        model = Dish
        fields = (
            'img',
            'name',
            'availability',
            'description',
            'price',
            'preparation_time',
        )
        labels = {
            'img':              'Immagine del piatto',
            'name':             'Nome del piatto',
            'availability':     'Dispponibilità',
            'description':      'Descrizione',
            'price':            'Prezzo',
            'preparation_time': 'Tempo di preparazione',
        }


class PaymentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(
            Submit('submit', 'Invia', css_class='btn btn-success payment-button')
        )

    class Meta:
        model = Order
        fields = (
            'customer_floor_flat_nb',
            'customer_number',
            'instructions',
            'cc_number',

        )
        labels = {
            'customer_floor_flat_nb':   'Piano e interno',
            'customer_number':          'Numero di telefono',
            'instructions':             'Istruzioni per il fattorino',
            'cc_number':                'Numero carta',
        }

restaurants/views.py
import datetime
import json

import pytz
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db import IntegrityError
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView
from django_tables2 import RequestConfig

from custom_users.models import Address, CustomUser
from food_delivery import settings
from food_delivery.email_settings import EMAIL_HOST_USER
from restaurants.forms import RestaurantForm, PaymentForm, DishForm
from restaurants.models import Dish, OrderedDish, Review
from restaurants.tables import *


# ------------------ Creation of restaurants -------------------

class RestaurantCreateView(CreateView):
    """
    Handles the creation of new restaurants
    """
    form_class = RestaurantForm
    template_name = 'restaurants/add_restaurant.html'

    def form_valid(self, form):
        restaurateur = self.request.user
        form.instance.restaurateur = restaurateur
        try:
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request, 'È già stato inserito un ristorante con questo nome!')
            return self.form_invalid(form)

    def get_success_url(self):
        messages.success(self.request, 'Nuovo ristorante aggiunto.')
        messages.warning(
            self.request,
            'I ristoranti non verranno visualizzati dai clienti fino a quando non vengono aggiunti dei piatti.'
        )
        return reverse("restaurants:restaurants-managing")

# ---------------------------------------------------------------


# ------------------ Creation of dishes -------------------

class DishCreateView(CreateView):
    """
    Handles the creation of new dishes
    """
    form_class = DishForm
    template_name = 'restaurants/add_dish.html'

    def get_context_data(self, **kwargs):
        context = super(DishCreateView, self).get_context_data(**kwargs)
        context['menu_managing_id'] = self.request.session.get('menu_managing_id', 0)
        return context

    def form_valid(self, form):
        form.instance.restaurant = Restaurant.objects.get(id=self.kwargs.get('restaurant_id', None))
        try:
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request, 'È già stato inserito un piatto con questo nome!')
            return self.form_invalid(form)

    def get_success_url(self):
        messages.success(self.request, 'Nuovo piatto aggiunto.')
        return reverse("restaurants:menu-managing", args=(self.kwargs.get('restaurant_id', None),))

# ----------------------------------------------------------


# ------------------ Restaurants management -------------------

def get_max_delivery_time(restaurant, travel_time):
    """
    Returns the delivery time calculated as the maximum preparation time for the dishes plus the travel time
    from the restaurant to the customer's house
    :param restaurant: restaurant
    :param travel_time: travel time from the restaurant to the customer's house
    :return: delivery time in minutes
    """
    restaurant_dishes = Dish.objects.filter(restaurant=restaurant).filter(availability=True)
    max_preparation_time = 0
    for dish in restaurant_dishes:
        if dish.preparation_time > max_preparation_time:
            max_preparation_time = dish.preparation_time
    return max_preparation_time + travel_time


def restaurants(request, pk):
    """
    Shows the restaurant page with his data, the distance and travel time from the customer, the average rating,
    the dishes, the shopping cart, the rating input system (that can only be accessed by authenticated customers that
    made an order to the restaurant) and all the past ratings (that can only be accessed by authenticated customers)
    """
    restaurant = Restaurant.objects.get(id=pk)
    request.session['restaurant_id'] = restaurant.id
    dishes = Dish.objects.filter(restaurant=pk)
    user = request.user
    user_authenticated = False
    if user.is_authenticated:
        user_authenticated = True
    user_address = request.session.get('input_address', None)

    # Delivery info
    distance_duration = request.session.get('distance_duration'+pk.__str__(), None)
    if request.user.is_authenticated and request.user.is_restaurateur:
        delivery_time = '*Tempi di spedizione*'
        distance = '*Distanza*'
    else:
        distance = round(distance_duration.get('distance', None), 1)
        travel_time = distance_duration.get('duration', None)
        request.session['travel_time'] = travel_time
        delivery_time = int(get_max_delivery_time(restaurant, travel_time))
        # request.session['delivery_time'] = delivery_time

    # Cart info
    cart_elements_dict = request.session.get('cart_elements', None)
    cart_elements = list()
    cart_restaurant = ''
    if cart_elements_dict != None:
        cart_elements = cart_elements_dict.get('elements', {})
        cart_restaurant = int(cart_elements_dict.get('restaurant', '0'))

    # Review info
    user_made_order = False
    user_reviewed_restaurant = False
    user_review = []
    user = request.user
    if user.is_authenticated:
        order = Order.objects.filter(restaurant=restaurant).filter(customer=user)
        if len(order) != 0:
            user_made_order = True
        user_reviews = Review.objects.filter(reviewer=user)
        if len(user_reviews) != 0:
            user_review = user_reviews.filter(restaurant=restaurant)
        if len(user_review) != 0:
            user_reviewed_restaurant = True
            user_review = user_reviews.get(restaurant=restaurant)
        user_name = user.first_name
    else:
        user_name = ''
    reviews = Review.objects.filter(restaurant=restaurant.id)

    # Rating info
    ratings_total = 0
    reviews_number = len(reviews)
    for rating in reviews.values_list('rating', flat=True):
        ratings_total += rating
    if reviews_number != 0:
        average_rating = round(ratings_total/len(reviews), 1)
    else:
        average_rating = 0
    if user_authenticated and user_reviewed_restaurant:
        user_rating = reviews.get(reviewer=user).rating
    else:
        user_rating = None

    cart_total = request.session.get('cart_elements', {}).get('total', 0.0)

    context = {
        'restaurant': restaurant, 'dishes': dishes, 'media_url': settings.MEDIA_URL, 'user_address': user_address,
        'delivery_time': delivery_time, 'cart_restaurant': cart_restaurant, 'cart_elements': cart_elements,
        'cart_elements_number': len(cart_elements), 'user_made_order': user_made_order,
        'user_reviewed_restaurant': user_reviewed_restaurant, 'user_review': user_review,
        'user_authenticated': user_authenticated, 'reviews': reviews, 'stars_number': [1,2,3,4,5],
        'average_rating': average_rating, 'reviews_number': reviews_number, 'distance': distance,
        'cart_total': cart_total, 'user_name': user_name, 'user_rating': user_rating
    }

    return render(request, 'restaurants/restaurant_page.html', context)


def modify_restaurant(request, id=None, template_name='restaurants/modify_restaurant.html'):
    """
    Handles the modification of a restaurant
    """
    if id:
        restaurant = get_object_or_404(Restaurant, pk=id)
        if restaurant.restaurateur != request.user:
            return HttpResponseForbidden()
    else:
        return

    form = RestaurantForm(request.POST or None, instance=restaurant)
    if request.POST and form.is_valid():
        form.save()

        # Save was successful, so redirect to another page
        messages.success(request, 'Ristorante modificato.')
        redirect_url = reverse('restaurants:restaurants-managing')
        return redirect(redirect_url)

    name = restaurant.name
    return render(request, template_name, {
        'form': form,
        'name': name,
    })


def remove_restaurant(request, id):
    """
    Handles the removal of a restaurant
    """
    Restaurant.objects.get(id=id).delete()
    messages.success(request, 'Ristorante rimosso.')
    return redirect('restaurants:restaurants-managing')


def restaurants_managing(request):
    """
    Shows the restaurateur all the restaurants that he added to the platform and gives him the opportunity to modify
    them, delete them or add new ones.
    """
    restaurateurs_restaurants = Restaurant.objects.filter(restaurateur=request.user)
    restaurants_number = len(restaurateurs_restaurants)
    table = RestaurantsTable(restaurateurs_restaurants)
    RequestConfig(request).configure(table)
    context = {'table': table, 'user_name': request.user.first_name, 'restaurants_number': restaurants_number}
    return render(request, 'restaurants/restaurants_managing.html', context)

# ---------------------------------------------------------


# ------------------ Menu management -------------------

def menu_managing(request, id=0):
    """
    Shows the restaurateur all the dishes that he added to the restaurants and gives him the opportunity to modify
    them, delete them or add new ones.
    """
    request.session['menu_managing_id'] = id
    restaurateurs_restaurants = Restaurant.objects.filter(restaurateur=request.user)
    if id.__str__() == '0':
        restaurateurs_menu = Dish.objects.filter(restaurant=restaurateurs_restaurants[0])
        restaurant = restaurateurs_restaurants[0]
    else:
        restaurateurs_menu = Dish.objects.filter(restaurant=id.__str__())
        restaurant = Restaurant.objects.get(id=id)
    multiple_restaurants = False
    if len(restaurateurs_restaurants) > 1:
        multiple_restaurants = True
    dishes_number = len(restaurateurs_menu)
    table = MenuTable(restaurateurs_menu)

restaurants/templates/restaurants/django_tables_templates/table_dish_remove.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{ record.id }}">
    <i class="fas fa-trash mr-1"></i>
    Elimina
</button>

<!-- Modal -->
<div class="modal" id="deleteModal{{ record.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-full-height modal-bottom modal-notify modal-danger" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #ff3547; box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);"><i class="fas fa-trash-alt fa-2x"></i>
        <h5 class="modal-title" id="exampleModalLabel">{{ record.titolo }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          Sicuro di voler rimuovere il piatto?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <a  href="{% url 'restaurants:remove-dish' record.id %}" type="button" class="btn btn-danger">Rimuovi</a>
      </div>
    </div>
  </div>
</div>

restaurants/templates/restaurants/django_tables_templates/table_menu_managing.html
<a class="btn btn-info btn-sm" href="{% url 'restaurants:menu-managing' record.id %}">
    <i class="fas fa-utensils mr-1"></i>
    Gestisci il menu
</a>

restaurants/templates/restaurants/django_tables_templates/table_modify_dish.html
<a class="btn btn-warning btn-sm" href="{% url 'restaurants:modify-dish' record.id %}">
    <i class="fas fa-wrench mr-1"></i>
    Modifica
</a>

restaurants/templates/restaurants/django_tables_templates/table_modify_restaurant.html
<a class="btn btn-warning btn-sm" href="{% url 'restaurants:modify-restaurant' record.id %}">
    <i class="fas fa-wrench mr-1"></i>
    Modifica
</a>

restaurants/templates/restaurants/django_tables_templates/table_order_accept.html
<a class="btn btn-success btn-sm" href="{% url 'restaurants:order-accept' record.id %}">
    <i class="fas fa-check"></i>
    Accetta
</a>

restaurants/templates/restaurants/django_tables_templates/table_order_details.html
<a class="btn btn-info btn-sm" href="{% url 'restaurants:orders-details' record.id %}">
    <i class="fas fa-info-circle mr-1"></i>
    Dettagli
</a>

restaurants/templates/restaurants/django_tables_templates/table_order_done.html
<a class="btn btn-success btn-sm" href="{% url 'restaurants:order-done' record.id %}">
    <i class="fas fa-check"></i>
    Terminato
</a>

restaurants/templates/restaurants/django_tables_templates/table_order_remove.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{ record.id }}">
    <i class="fas fa-trash mr-1"></i>
    Elimina
</button>

<!-- Modal -->
<div class="modal" id="deleteModal{{ record.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-full-height modal-bottom modal-notify modal-danger" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #ff3547; box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);"><i class="fas fa-trash-alt fa-2x"></i>
        <h5 class="modal-title" id="exampleModalLabel">{{ record.titolo }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          Sicuro di voler rimuovere l'ordine?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <a  href="{% url 'restaurants:remove-order' record.id %}" type="button" class="btn btn-danger">Rimuovi</a>
      </div>
    </div>
  </div>
</div>

restaurants/templates/restaurants/django_tables_templates/table_restaurant_preview.html
<a class="btn btn-info btn-sm" href="{% url 'restaurants:restaurant-page' record.id %}">
    <i class="fas fa-columns mr-1"></i>
    Preview
</a>

restaurants/templates/restaurants/django_tables_templates/table_restaurant_remove.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{ record.id }}">
    <i class="fas fa-trash mr-1"></i>
    Rimuovi ristorante
</button>

<!-- Modal -->
<div class="modal" id="deleteModal{{ record.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-full-height modal-bottom modal-notify modal-danger" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #ff3547; box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);"><i class="fas fa-trash-alt fa-2x"></i>
        <h5 class="modal-title" id="exampleModalLabel">{{ record.titolo }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          Sicuro di voler rimuovere il ristorante?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
        <a  href="{% url 'restaurants:remove-restaurant' record.id %}" type="button" class="btn btn-danger">Rimuovi</a>
      </div>
    </div>
  </div>
</div>