custom_users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from custom_users import views

app_name = 'custom_users'

urlpatterns = [
    path('customer_home/', views.customer_home, name='customer-home'),
    path('restaurateur_home/', views.restaurateur_home, name='restaurateur-home'),
    path('customer_users/register/', views.CustomerUserCreateView.as_view(), name='register-customer-user'),

    path('restaurateur_users/register/', views.RestaurateurUserCreateView.as_view(), name='register-restaurateur-user'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('customer_orders_managing/', views.customer_orders_managing, name='customer-orders-managing'),
    path('customer_accepted_orders_managing/', views.customer_accepted_orders, name='customer-accepted-orders'),
    path('<str:id>/customer_order_details/', views.customer_order_details, name='customer-order-details'),
    path('<str:id>/customer_modify_order/', views.customer_modify_order, name='customer-modify-order'),
    path('<str:id>/customer_cancel_order/', views.customer_cancel_order, name='customer-cancel-order'),
    path('<str:id>/customer_order_remove/', views.customer_order_remove, name='customer-order-remove'),

    path('modify_order/ajax_get_cart_data/', views.ajax_get_cart_data, name='ajax-get-cart-data'),

]

food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from food_delivery import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('input_address/', views.InputAddress.as_view(), name='input-address'),
    path('restaurants_in_range/', views.show_restaurants_in_range, name='show_restaurants_in_range'),
    path('admin/', admin.site.urls),
    path('auth_user/', include('custom_users.urls')),
    path('restaurants/', include('restaurants.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.template.context_processors import static
from django.urls import path, include

from restaurants import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'restaurants'

urlpatterns = [
    path('add_restaurant/', views.RestaurantCreateView.as_view(), name='add-restaurant'),
    path('remove_restaurant/<str:id>/', views.remove_restaurant, name='remove-restaurant'),
    path('<str:restaurant_id>/add_dish/', views.DishCreateView.as_view(), name='add-dish'),

    path('<str:pk>/', views.restaurants, name='restaurant-page'),
    path('restaurateur/restaurants_managing/', views.restaurants_managing, name='restaurants-managing'),
    path('<str:id>/modify_restaurant/', views.modify_restaurant, name='modify-restaurant'),

    path('<str:restaurant_id_order>/orders_managing/', views.orders_managing, name='orders-managing'),
    path('<str:restaurant_id_order>/accepted_orders_managing/', views.accepted_orders_managing, name='accepted-orders-managing'),
    path('<str:restaurant_id_order>/done_orders_managing/', views.done_orders_managing, name='done-orders-managing'),
    path('<str:id>/orders_details/', views.order_details, name='orders-details'),
    path('order_done/<str:id>/', views.order_done, name='order-done'),
    path('order_accept/<str:id>/', views.order_accept, name='order-accept'),
    path('remove_order/<str:id>/', views.remove_order, name='remove-order'),
    path('checkout/payment/', views.Payment.as_view(), name='payment'),

    path('<str:id>/menu_managing/', views.menu_managing, name='menu-managing'),
    path('<str:id>/modify_dish/', views.modify_dish, name='modify-dish'),
    path('<str:id>/remove_dish/', views.remove_dish, name='remove-dish'),

    path('checkout/ajax_get_cart_data/', views.ajax_get_cart_data, name='ajax-get-cart-data'),
    path('', views.ajax_get_rating_data, name='ajax-get-rating-data'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"
          href="{% static 'css/base.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body>

{% block content%}

    <nav class="navbar my-navbar navbar-expand-lg navbar-light bg-white">
        <div class="container">
            <a class="navbar-brand" id="home-logo" href="{% url 'home' %}" >Food delivery</a>
            <button
                    class="navbar-toggler border-0"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span
                            class="iconify bar-icon"
                            data-icon="fa-solid:bars"
                            data-inline="false">
                    </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    {% if request.user.is_restaurateur %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'restaurants:restaurants-managing' %}">Gestione ristoranti<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'restaurants:menu-managing' 0 %}">Gestione menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'restaurants:orders-managing' 0 %}">Gestione ordini</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'restaurants:accepted-orders-managing' 0 %}">Gestione ordini accettati</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'restaurants:done-orders-managing' 0 %}">Ordini terminati</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user_name }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'custom_users:logout' %}">Logout</a>
                            </div>
                        </li>
                    {% else %}

                        {% block search-bar %}
                            <li class="nav-item">
                                <a class="btn btn-dark" id="find_a_meal_btn" href="{% url 'input-address' %}"><i class="fas fa-utensils mr-2"></i>Trova un pasto</a>
                            </li>
                        {% endblock %}

                            <!-- Shopping cart button -->
                            {% if cart_total == 0.0 %}
                                <li class="nav-item">
                                    <a class="btn btn-outline-dark disabled mx-2" id="shopping_cart_btn" href="{% url 'restaurants:payment' %}?next={{ request.path }}" ><i class="fas fa-shopping-cart mr-2"></i>{{ cart_total }}€</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="btn btn-outline-dark mx-2" id="shopping_cart_btn" href="{% url 'restaurants:payment' %}?next={{ request.path }}" ><i class="fas fa-shopping-cart mr-2"></i>{{ cart_total }}€</a>
                                </li>
                            {% endif %}
                            <!--------------------->
                        {% block user-section %}
                            <!-- Nav bar buttons -->
                            {% if request.user.is_authenticated %}
                                {% if user.is_customer %}
                                    <!-- dropdown menu to access and orders' management -->
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle active" href="#" id="customer-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{ user_name }}
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <a class="dropdown-item" href="{% url 'custom_users:logout' %}">Logout</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{% url 'custom_users:customer-orders-managing' %}">Gestione ordini non accettati</a>
                                            <a class="dropdown-item" href="{% url 'custom_users:customer-accepted-orders' %}">Ordini accettati</a>
                                        </div>
                                    </li>
                                    <!-------------------------------------------------------------->
                                {% endif %}
                            {% else %}
                                <li class="nav-item">
                                    <a id="home-login" class="nav-link active" href="{% url 'custom_users:login' %}">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a id="home-signup" class="nav-link active" href="{% url 'custom_users:register-customer-user' %}">Registrati</a>
                                </li>
                                <li class="nav-item">
                                    <a id="home-signup" class="nav-link active" href="{% url 'custom_users:register-restaurateur-user' %}">Diventa partner</a>
                                </li>
                            {% endif %}
                            <!-------------------->
                        {% endblock %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}

{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

{#<script type="text/javascript" src="{% static 'js/cart_updater.js' %}"></script>#}

{% block javascript %}

{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block title %}Homepage{% endblock %}

{% block search-bar %}
{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

        <div class="find-a-meal-container">
            <div class="find-a-meal-container-inner">
                <a class="btn btn-dark" id="find_a_meal_btn_home" href="{% url 'input-address' %}"><i class="fas fa-utensils mr-2"></i>Trova un pasto</a>
            </div>
        </div>
{% endblock %}

templates/input_address.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Inserimento indirizzo{% endblock %}

{% block content %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <a type="button" action="action"  onclick="window.history.go(-1); return false;" class="btn btn-outline-dark"><i class="fas fa-arrow-left mr-2"></i>Indietro</a>

    <div class="container">
    <h2 class="mx-3 my-3">Inserisci l'indirizzo di spedizione</h2>
    <br>
        {% csrf_token %}
        {% crispy form %}
    </div>
{% endblock %}

templates/show_restaurants_in_range.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/show_restaurants_in_range.css' %}">
{% endblock %}

{% block title %}Consegna a domicilio in via {{ customer_street }}{% endblock %}

{% block body %}
    <!-- Show django messages -->
    {% if messages %}
        <ul class="messages" style="padding: 0px;">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
    {% endif %}
    <!------------------------->

    <h2 class="my-3 mx-3">Ristoranti che consegnano in via {{ customer_street }}</h2>
    {% for restaurant in restaurants_in_range %}
        <a class="btn btn-dark mx-3 restaurant_button" href="{% url 'restaurants:restaurant-page' pk=restaurant.id %}">
        <img id="restaurant_logo_in_btn" class="m-2" src="{{ media_url }}{{ restaurant.logo }}">
            <h5>{{ restaurant.name }}</h5>
            <p>
                Via {{ restaurant.street }} {{ restaurant.house_number }}, {{ restaurant.city }}
            </p>
        </a>
    {%  endfor %}
{% endblock %}